import type { Metadata } from "next";
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { PublicConfigProvider } from "./PublicConfigProvider";
import { ToasterWrapper } from "./ToasterWrapper";

const onest = localFont({
  src: "./fonts/Onest/Onest-VariableFont_wght.ttf",
  variable: "--font-onest",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} antialiased`}>
        <PublicConfigProvider>
          {children}
          <ToasterWrapper />
        </PublicConfigProvider>
      </body>
    </html>
  );
}
